<?php
/**
 * File Manager Component
 * 
 * Reusable component for displaying file upload and management interface
 * 
 * Usage:
 * $entityType = 'project'; // or 'feature' or 'task'
 * $entityId = 123;
 * include 'includes/file-manager-component.php';
 */

// Validate required variables
if (!isset($entityType) || !isset($entityId)) {
    throw new Exception('File manager component requires $entityType and $entityId variables');
}

if (!in_array($entityType, ['project', 'feature', 'task'])) {
    throw new Exception('Invalid entity type for file manager');
}

$entityId = (int)$entityId;
if ($entityId <= 0) {
    throw new Exception('Invalid entity ID for file manager');
}

// Generate unique container ID to support multiple file managers on same page
$containerId = 'file-manager-container-' . $entityType . '-' . $entityId;
?>

<!-- File Manager Component -->
<div class="row mt-4">
    <div class="col-12">
        <div id="<?php echo $containerId; ?>">
            <!-- File manager interface will be generated by JavaScript -->
            <div class="text-center py-4">
                <div class="file-loading"></div>
                <p class="mt-2 text-muted">Loading file manager...</p>
            </div>
        </div>
    </div>
</div>

<!-- Include file manager JavaScript -->
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Initialize file manager for this entity
    const container = document.getElementById('<?php echo $containerId; ?>');
    if (container) {
        // Set the container ID temporarily for the FileManager class
        const originalContainer = document.getElementById('file-manager-container');
        container.id = 'file-manager-container';
        
        // Initialize file manager
        fileManager = new FileManager('<?php echo $entityType; ?>', <?php echo $entityId; ?>);
        
        // Restore original ID
        container.id = '<?php echo $containerId; ?>';
    }
});
</script>

<!-- File Manager Styles (only include once per page) -->
<script>
if (!document.getElementById('file-manager-styles-loaded')) {
    const link = document.createElement('script');
    link.id = 'file-manager-styles-loaded';
    link.src = '/assets/js/file-manager.js';
    document.head.appendChild(link);
}
</script>

<style>
/* Component-specific styles to ensure file manager displays correctly */
#<?php echo $containerId; ?> .card {
    border: 1px solid var(--border-bg);
    border-radius: var(--border-radius);
    background: var(--white);
    box-shadow: var(--box-shadow);
}

#<?php echo $containerId; ?> .card-header {
    background: var(--bg-shade1);
    border-bottom: 1px solid var(--border-bg);
    padding: 15px 20px;
}

#<?php echo $containerId; ?> .card-body {
    padding: 20px;
}
</style><?php
/**
 * Example Usage in any page:
 * 
 * For a project page:
 * $entityType = 'project';
 * $entityId = $project['id'];
 * include 'includes/file-manager-component.php';
 * 
 * For a feature page:
 * $entityType = 'feature';
 * $entityId = $feature['id'];
 * include 'includes/file-manager-component.php';
 * 
 * For a task page:
 * $entityType = 'task';
 * $entityId = $task['id'];
 * include 'includes/file-manager-component.php';
 */
?>